### ISSUE TITLE
Build fails due to unresolvable resources

### ISSUE THREAD

**Issue by marcelb98** [PhilippMatthes/manni-android#1]
Building the app fails with
`error: resource drawable/animation00000 (aka philippmatthes.com.manni:drawable/animation00000) not found.`
for animation00000 - 00019 in `res/drawable/spinner.xml`.

**Comment by PhilippMatthes** [comment]
Hi marcel, the animation is located in `https://github.com/PhilippMatthes/manni-android/tree/master/app/src/main/res/drawable-xxhdpi`.
